palavras_reservadas = {
    'Falso'      : 'False',
    'Nada'       : 'None',
    'Verdade'    : 'True',
    ' tambem '     : ' and ',
    ' como '       : ' as ',
    'quebra'     : 'break',
    'classe '      : 'class',
    'continua'   : 'continue',
    'def '       : 'def ',
    'del'        : 'del',
    'oucaso'     : 'elif',
    'senao:'       : 'else:',
    'exceto'     : 'except',
    'entao'      : 'finally',
    'por'        : 'for',
    'de '         : 'from ',
    'global '     : 'global ',
    'caso'       : 'if',
    'importa '    : 'import ',
    ' em '        : ' in ',
    ' e '         : ' is ',
    ' nao '        : ' not ',
    ' ou '         : ' or ',
    'passa'      : 'pass',
    'projeta'    : 'raise',
    'retorna '    : 'return ',
    'tenta'      : 'try',
    'durante'    : 'while',
    'com '       : 'with '
}

funcoes = {
    'todo'            : 'all',
    'bool('            : 'bool(',
    'metododeclasse'  : 'classmethod',
    'dicio('           : 'dict(',
    'dir('             : 'dir(',
    'enumera('         : 'enumerate(',
    'exec('            : 'exec(',
    'filtro('          : 'filter(',
    'flutuante('       : 'float(',
    'formata('         : 'format(',
    'globais('         : 'globals(',
    'hexa('            : 'hex(',
    'entrada('         : 'input(',
    'int('             : 'int(',
    'tam('             : 'len(',
    'lista('           : 'list(',
    'abre('            : 'open(',
    'mostra('          : 'print(',
    'faixa('           : 'range(',
    'arredonda('       : 'round(',
    'define('          : 'set(',
    'metodostatico'   : 'staticmethod',
    'txt('             : 'str(',
    'soma('            : 'sum(',
    'super('           : 'super(',
    'tupla('           : 'tuple(',
    'tipo('            : 'type(',
}
